apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    name: results-service
    app: demo-voting-app
spec: 
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    name: results-app-pod
    app: demo-voting-app